// 
// Decompiled by Procyon v0.5.36
// 

package com.google.android.systemui.statusbar.phone;

import dagger.internal.Preconditions;
import dagger.Lazy;
import dagger.internal.DoubleCheck;
import com.android.systemui.keyguard.WakefulnessLifecycle;
import com.android.systemui.volume.VolumeComponent;
import com.android.systemui.statusbar.notification.VisualStabilityManager;
import com.android.keyguard.ViewMediatorCallback;
import com.android.systemui.statusbar.VibratorHelper;
import com.android.systemui.statusbar.policy.UserSwitcherController;
import com.android.systemui.statusbar.policy.UserInfoControllerImpl;
import java.util.concurrent.Executor;
import android.os.Handler;
import com.android.systemui.statusbar.SuperStatusBarViewFactory;
import com.android.systemui.statusbar.phone.StatusBarTouchableRegionManager;
import com.android.systemui.statusbar.SysuiStatusBarStateController;
import com.android.systemui.statusbar.phone.StatusBarNotificationActivityStarter;
import com.android.systemui.statusbar.phone.StatusBarKeyguardViewManager;
import com.android.systemui.statusbar.phone.StatusBarIconController;
import com.android.systemui.statusbar.phone.dagger.StatusBarComponent;
import com.google.android.systemui.smartspace.SmartSpaceController;
import com.android.systemui.statusbar.phone.ShadeController;
import com.google.android.systemui.LiveWallpaperScrimController;
import com.android.systemui.recents.ScreenPinningRequest;
import com.android.systemui.keyguard.ScreenLifecycle;
import com.google.android.systemui.reversecharging.ReverseChargingWindowController;
import com.android.systemui.statusbar.policy.RemoteInputQuickSettingsDisabler;
import com.android.systemui.statusbar.NotificationRemoteInputManager;
import com.android.systemui.recents.Recents;
import com.android.systemui.statusbar.PulseExpansionHandler;
import android.os.PowerManager;
import com.android.systemui.shared.plugins.PluginManager;
import com.android.systemui.plugins.PluginDependencyProvider;
import com.android.systemui.statusbar.phone.PhoneStatusBarPolicy;
import com.android.systemui.statusbar.notification.init.NotificationsController;
import com.android.systemui.statusbar.notification.NotificationWakeUpCoordinator;
import com.android.systemui.statusbar.NotificationViewHierarchyManager;
import com.android.systemui.statusbar.phone.NotificationShadeWindowController;
import com.android.systemui.statusbar.NotificationShadeDepthController;
import com.android.systemui.statusbar.NotificationMediaManager;
import com.android.systemui.statusbar.notification.logging.NotificationLogger;
import com.android.systemui.statusbar.notification.interruption.NotificationInterruptStateProvider;
import com.android.systemui.statusbar.notification.row.NotificationGutsManager;
import com.android.systemui.statusbar.notification.interruption.NotificationAlertingManager;
import com.android.systemui.statusbar.policy.NetworkController;
import com.android.systemui.statusbar.NavigationBarController;
import com.android.internal.logging.MetricsLogger;
import com.android.systemui.statusbar.phone.LockscreenWallpaper;
import com.android.systemui.statusbar.phone.LockscreenLockIconController;
import com.android.systemui.statusbar.NotificationLockscreenUserManager;
import com.android.systemui.statusbar.phone.LightsOutNotifController;
import com.android.systemui.statusbar.phone.LightBarController;
import com.android.systemui.keyguard.KeyguardViewMediator;
import com.android.keyguard.KeyguardUpdateMonitor;
import com.android.systemui.statusbar.policy.KeyguardStateController;
import com.android.systemui.statusbar.phone.KeyguardLiftController;
import com.android.systemui.statusbar.KeyguardIndicationController;
import com.android.systemui.statusbar.phone.KeyguardDismissUtil;
import com.android.systemui.statusbar.phone.KeyguardBypassController;
import com.android.systemui.InitController;
import com.android.systemui.statusbar.phone.HeadsUpManagerPhone;
import com.android.systemui.statusbar.phone.NotificationGroupManager;
import com.android.systemui.plugins.FalsingManager;
import com.android.systemui.statusbar.policy.ExtensionController;
import com.android.systemui.statusbar.notification.DynamicPrivacyController;
import com.android.systemui.statusbar.phone.DozeServiceHost;
import com.android.systemui.statusbar.phone.DozeScrimController;
import com.android.systemui.statusbar.phone.DozeParameters;
import com.android.systemui.stackdivider.Divider;
import java.util.Optional;
import android.util.DisplayMetrics;
import com.android.systemui.keyguard.DismissCallbackRegistry;
import com.android.systemui.statusbar.policy.DeviceProvisionedController;
import com.android.systemui.plugins.DarkIconDispatcher;
import android.content.Context;
import com.android.systemui.statusbar.policy.ConfigurationController;
import com.android.systemui.statusbar.CommandQueue;
import com.android.systemui.colorextraction.SysuiColorExtractor;
import com.android.systemui.statusbar.notification.interruption.BypassHeadsUpNotifier;
import com.android.systemui.bubbles.BubbleController;
import com.android.systemui.broadcast.BroadcastDispatcher;
import com.android.systemui.statusbar.phone.BiometricUnlockController;
import com.android.systemui.statusbar.policy.BatteryController;
import com.android.systemui.statusbar.phone.AutoHideController;
import com.android.systemui.assist.AssistManager;
import javax.inject.Provider;
import dagger.internal.Factory;

public final class StatusBarGoogleModule_ProvideStatusBarFactory implements Factory<StatusBarGoogle>
{
    private final Provider<AssistManager> assistManagerLazyProvider;
    private final Provider<AutoHideController> autoHideControllerProvider;
    private final Provider<BatteryController> batteryControllerProvider;
    private final Provider<BiometricUnlockController> biometricUnlockControllerLazyProvider;
    private final Provider<BroadcastDispatcher> broadcastDispatcherProvider;
    private final Provider<BubbleController> bubbleControllerProvider;
    private final Provider<BypassHeadsUpNotifier> bypassHeadsUpNotifierProvider;
    private final Provider<SysuiColorExtractor> colorExtractorProvider;
    private final Provider<CommandQueue> commandQueueProvider;
    private final Provider<ConfigurationController> configurationControllerProvider;
    private final Provider<Context> contextProvider;
    private final Provider<DarkIconDispatcher> darkIconDispatcherProvider;
    private final Provider<DeviceProvisionedController> deviceProvisionedControllerProvider;
    private final Provider<DismissCallbackRegistry> dismissCallbackRegistryProvider;
    private final Provider<DisplayMetrics> displayMetricsProvider;
    private final Provider<Optional<Divider>> dividerOptionalProvider;
    private final Provider<DozeParameters> dozeParametersProvider;
    private final Provider<DozeScrimController> dozeScrimControllerProvider;
    private final Provider<DozeServiceHost> dozeServiceHostProvider;
    private final Provider<DynamicPrivacyController> dynamicPrivacyControllerProvider;
    private final Provider<ExtensionController> extensionControllerProvider;
    private final Provider<FalsingManager> falsingManagerProvider;
    private final Provider<NotificationGroupManager> groupManagerProvider;
    private final Provider<HeadsUpManagerPhone> headsUpManagerPhoneProvider;
    private final Provider<InitController> initControllerProvider;
    private final Provider<KeyguardBypassController> keyguardBypassControllerProvider;
    private final Provider<KeyguardDismissUtil> keyguardDismissUtilProvider;
    private final Provider<KeyguardIndicationController> keyguardIndicationControllerProvider;
    private final Provider<KeyguardLiftController> keyguardLiftControllerProvider;
    private final Provider<KeyguardStateController> keyguardStateControllerProvider;
    private final Provider<KeyguardUpdateMonitor> keyguardUpdateMonitorProvider;
    private final Provider<KeyguardViewMediator> keyguardViewMediatorProvider;
    private final Provider<LightBarController> lightBarControllerProvider;
    private final Provider<LightsOutNotifController> lightsOutNotifControllerProvider;
    private final Provider<NotificationLockscreenUserManager> lockScreenUserManagerProvider;
    private final Provider<LockscreenLockIconController> lockscreenLockIconControllerProvider;
    private final Provider<LockscreenWallpaper> lockscreenWallpaperLazyProvider;
    private final Provider<MetricsLogger> metricsLoggerProvider;
    private final Provider<NavigationBarController> navigationBarControllerProvider;
    private final Provider<NetworkController> networkControllerProvider;
    private final Provider<NotificationAlertingManager> notificationAlertingManagerProvider;
    private final Provider<NotificationGutsManager> notificationGutsManagerProvider;
    private final Provider<NotificationInterruptStateProvider> notificationInterruptionStateProvider;
    private final Provider<NotificationLogger> notificationLoggerProvider;
    private final Provider<NotificationMediaManager> notificationMediaManagerProvider;
    private final Provider<NotificationShadeDepthController> notificationShadeDepthControllerLazyProvider;
    private final Provider<NotificationShadeWindowController> notificationShadeWindowControllerProvider;
    private final Provider<NotificationViewHierarchyManager> notificationViewHierarchyManagerProvider;
    private final Provider<NotificationWakeUpCoordinator> notificationWakeUpCoordinatorProvider;
    private final Provider<NotificationsController> notificationsControllerProvider;
    private final Provider<PhoneStatusBarPolicy> phoneStatusBarPolicyProvider;
    private final Provider<PluginDependencyProvider> pluginDependencyProvider;
    private final Provider<PluginManager> pluginManagerProvider;
    private final Provider<PowerManager> powerManagerProvider;
    private final Provider<PulseExpansionHandler> pulseExpansionHandlerProvider;
    private final Provider<Optional<Recents>> recentsProvider;
    private final Provider<NotificationRemoteInputManager> remoteInputManagerProvider;
    private final Provider<RemoteInputQuickSettingsDisabler> remoteInputQuickSettingsDisablerProvider;
    private final Provider<Optional<ReverseChargingWindowController>> reverseChargingWindowControllerOptionalProvider;
    private final Provider<ScreenLifecycle> screenLifecycleProvider;
    private final Provider<ScreenPinningRequest> screenPinningRequestProvider;
    private final Provider<LiveWallpaperScrimController> scrimControllerProvider;
    private final Provider<ShadeController> shadeControllerProvider;
    private final Provider<SmartSpaceController> smartSpaceControllerProvider;
    private final Provider<StatusBarComponent.Builder> statusBarComponentBuilderProvider;
    private final Provider<StatusBarIconController> statusBarIconControllerProvider;
    private final Provider<StatusBarKeyguardViewManager> statusBarKeyguardViewManagerProvider;
    private final Provider<StatusBarNotificationActivityStarter.Builder> statusBarNotificationActivityStarterBuilderProvider;
    private final Provider<SysuiStatusBarStateController> statusBarStateControllerProvider;
    private final Provider<StatusBarTouchableRegionManager> statusBarTouchableRegionManagerProvider;
    private final Provider<SuperStatusBarViewFactory> superStatusBarViewFactoryProvider;
    private final Provider<Handler> timeTickHandlerProvider;
    private final Provider<Executor> uiBgExecutorProvider;
    private final Provider<UserInfoControllerImpl> userInfoControllerImplProvider;
    private final Provider<UserSwitcherController> userSwitcherControllerProvider;
    private final Provider<VibratorHelper> vibratorHelperProvider;
    private final Provider<ViewMediatorCallback> viewMediatorCallbackProvider;
    private final Provider<VisualStabilityManager> visualStabilityManagerProvider;
    private final Provider<VolumeComponent> volumeComponentProvider;
    private final Provider<WakefulnessLifecycle> wakefulnessLifecycleProvider;
    private final Provider<WallpaperNotifier> wallpaperNotifierProvider;
    
    public StatusBarGoogleModule_ProvideStatusBarFactory(final Provider<SmartSpaceController> smartSpaceControllerProvider, final Provider<WallpaperNotifier> wallpaperNotifierProvider, final Provider<Optional<ReverseChargingWindowController>> reverseChargingWindowControllerOptionalProvider, final Provider<Context> contextProvider, final Provider<NotificationsController> notificationsControllerProvider, final Provider<LightBarController> lightBarControllerProvider, final Provider<AutoHideController> autoHideControllerProvider, final Provider<KeyguardUpdateMonitor> keyguardUpdateMonitorProvider, final Provider<StatusBarIconController> statusBarIconControllerProvider, final Provider<PulseExpansionHandler> pulseExpansionHandlerProvider, final Provider<NotificationWakeUpCoordinator> notificationWakeUpCoordinatorProvider, final Provider<KeyguardBypassController> keyguardBypassControllerProvider, final Provider<KeyguardStateController> keyguardStateControllerProvider, final Provider<HeadsUpManagerPhone> headsUpManagerPhoneProvider, final Provider<DynamicPrivacyController> dynamicPrivacyControllerProvider, final Provider<BypassHeadsUpNotifier> bypassHeadsUpNotifierProvider, final Provider<FalsingManager> falsingManagerProvider, final Provider<BroadcastDispatcher> broadcastDispatcherProvider, final Provider<RemoteInputQuickSettingsDisabler> remoteInputQuickSettingsDisablerProvider, final Provider<NotificationGutsManager> notificationGutsManagerProvider, final Provider<NotificationLogger> notificationLoggerProvider, final Provider<NotificationInterruptStateProvider> notificationInterruptionStateProvider, final Provider<NotificationViewHierarchyManager> notificationViewHierarchyManagerProvider, final Provider<KeyguardViewMediator> keyguardViewMediatorProvider, final Provider<NotificationAlertingManager> notificationAlertingManagerProvider, final Provider<DisplayMetrics> displayMetricsProvider, final Provider<MetricsLogger> metricsLoggerProvider, final Provider<Executor> uiBgExecutorProvider, final Provider<NotificationMediaManager> notificationMediaManagerProvider, final Provider<NotificationLockscreenUserManager> lockScreenUserManagerProvider, final Provider<NotificationRemoteInputManager> remoteInputManagerProvider, final Provider<UserSwitcherController> userSwitcherControllerProvider, final Provider<NetworkController> networkControllerProvider, final Provider<BatteryController> batteryControllerProvider, final Provider<SysuiColorExtractor> colorExtractorProvider, final Provider<ScreenLifecycle> screenLifecycleProvider, final Provider<WakefulnessLifecycle> wakefulnessLifecycleProvider, final Provider<SysuiStatusBarStateController> statusBarStateControllerProvider, final Provider<VibratorHelper> vibratorHelperProvider, final Provider<BubbleController> bubbleControllerProvider, final Provider<NotificationGroupManager> groupManagerProvider, final Provider<VisualStabilityManager> visualStabilityManagerProvider, final Provider<DeviceProvisionedController> deviceProvisionedControllerProvider, final Provider<NavigationBarController> navigationBarControllerProvider, final Provider<AssistManager> assistManagerLazyProvider, final Provider<ConfigurationController> configurationControllerProvider, final Provider<NotificationShadeWindowController> notificationShadeWindowControllerProvider, final Provider<LockscreenLockIconController> lockscreenLockIconControllerProvider, final Provider<DozeParameters> dozeParametersProvider, final Provider<LiveWallpaperScrimController> scrimControllerProvider, final Provider<KeyguardLiftController> keyguardLiftControllerProvider, final Provider<LockscreenWallpaper> lockscreenWallpaperLazyProvider, final Provider<BiometricUnlockController> biometricUnlockControllerLazyProvider, final Provider<NotificationShadeDepthController> notificationShadeDepthControllerLazyProvider, final Provider<DozeServiceHost> dozeServiceHostProvider, final Provider<PowerManager> powerManagerProvider, final Provider<ScreenPinningRequest> screenPinningRequestProvider, final Provider<DozeScrimController> dozeScrimControllerProvider, final Provider<VolumeComponent> volumeComponentProvider, final Provider<CommandQueue> commandQueueProvider, final Provider<Optional<Recents>> recentsProvider, final Provider<StatusBarComponent.Builder> statusBarComponentBuilderProvider, final Provider<PluginManager> pluginManagerProvider, final Provider<Optional<Divider>> dividerOptionalProvider, final Provider<LightsOutNotifController> lightsOutNotifControllerProvider, final Provider<StatusBarNotificationActivityStarter.Builder> statusBarNotificationActivityStarterBuilderProvider, final Provider<ShadeController> shadeControllerProvider, final Provider<SuperStatusBarViewFactory> superStatusBarViewFactoryProvider, final Provider<StatusBarKeyguardViewManager> statusBarKeyguardViewManagerProvider, final Provider<ViewMediatorCallback> viewMediatorCallbackProvider, final Provider<InitController> initControllerProvider, final Provider<DarkIconDispatcher> darkIconDispatcherProvider, final Provider<Handler> timeTickHandlerProvider, final Provider<PluginDependencyProvider> pluginDependencyProvider, final Provider<KeyguardDismissUtil> keyguardDismissUtilProvider, final Provider<ExtensionController> extensionControllerProvider, final Provider<UserInfoControllerImpl> userInfoControllerImplProvider, final Provider<PhoneStatusBarPolicy> phoneStatusBarPolicyProvider, final Provider<KeyguardIndicationController> keyguardIndicationControllerProvider, final Provider<DismissCallbackRegistry> dismissCallbackRegistryProvider, final Provider<StatusBarTouchableRegionManager> statusBarTouchableRegionManagerProvider) {
        this.smartSpaceControllerProvider = smartSpaceControllerProvider;
        this.wallpaperNotifierProvider = wallpaperNotifierProvider;
        this.reverseChargingWindowControllerOptionalProvider = reverseChargingWindowControllerOptionalProvider;
        this.contextProvider = contextProvider;
        this.notificationsControllerProvider = notificationsControllerProvider;
        this.lightBarControllerProvider = lightBarControllerProvider;
        this.autoHideControllerProvider = autoHideControllerProvider;
        this.keyguardUpdateMonitorProvider = keyguardUpdateMonitorProvider;
        this.statusBarIconControllerProvider = statusBarIconControllerProvider;
        this.pulseExpansionHandlerProvider = pulseExpansionHandlerProvider;
        this.notificationWakeUpCoordinatorProvider = notificationWakeUpCoordinatorProvider;
        this.keyguardBypassControllerProvider = keyguardBypassControllerProvider;
        this.keyguardStateControllerProvider = keyguardStateControllerProvider;
        this.headsUpManagerPhoneProvider = headsUpManagerPhoneProvider;
        this.dynamicPrivacyControllerProvider = dynamicPrivacyControllerProvider;
        this.bypassHeadsUpNotifierProvider = bypassHeadsUpNotifierProvider;
        this.falsingManagerProvider = falsingManagerProvider;
        this.broadcastDispatcherProvider = broadcastDispatcherProvider;
        this.remoteInputQuickSettingsDisablerProvider = remoteInputQuickSettingsDisablerProvider;
        this.notificationGutsManagerProvider = notificationGutsManagerProvider;
        this.notificationLoggerProvider = notificationLoggerProvider;
        this.notificationInterruptionStateProvider = notificationInterruptionStateProvider;
        this.notificationViewHierarchyManagerProvider = notificationViewHierarchyManagerProvider;
        this.keyguardViewMediatorProvider = keyguardViewMediatorProvider;
        this.notificationAlertingManagerProvider = notificationAlertingManagerProvider;
        this.displayMetricsProvider = displayMetricsProvider;
        this.metricsLoggerProvider = metricsLoggerProvider;
        this.uiBgExecutorProvider = uiBgExecutorProvider;
        this.notificationMediaManagerProvider = notificationMediaManagerProvider;
        this.lockScreenUserManagerProvider = lockScreenUserManagerProvider;
        this.remoteInputManagerProvider = remoteInputManagerProvider;
        this.userSwitcherControllerProvider = userSwitcherControllerProvider;
        this.networkControllerProvider = networkControllerProvider;
        this.batteryControllerProvider = batteryControllerProvider;
        this.colorExtractorProvider = colorExtractorProvider;
        this.screenLifecycleProvider = screenLifecycleProvider;
        this.wakefulnessLifecycleProvider = wakefulnessLifecycleProvider;
        this.statusBarStateControllerProvider = statusBarStateControllerProvider;
        this.vibratorHelperProvider = vibratorHelperProvider;
        this.bubbleControllerProvider = bubbleControllerProvider;
        this.groupManagerProvider = groupManagerProvider;
        this.visualStabilityManagerProvider = visualStabilityManagerProvider;
        this.deviceProvisionedControllerProvider = deviceProvisionedControllerProvider;
        this.navigationBarControllerProvider = navigationBarControllerProvider;
        this.assistManagerLazyProvider = assistManagerLazyProvider;
        this.configurationControllerProvider = configurationControllerProvider;
        this.notificationShadeWindowControllerProvider = notificationShadeWindowControllerProvider;
        this.lockscreenLockIconControllerProvider = lockscreenLockIconControllerProvider;
        this.dozeParametersProvider = dozeParametersProvider;
        this.scrimControllerProvider = scrimControllerProvider;
        this.keyguardLiftControllerProvider = keyguardLiftControllerProvider;
        this.lockscreenWallpaperLazyProvider = lockscreenWallpaperLazyProvider;
        this.biometricUnlockControllerLazyProvider = biometricUnlockControllerLazyProvider;
        this.notificationShadeDepthControllerLazyProvider = notificationShadeDepthControllerLazyProvider;
        this.dozeServiceHostProvider = dozeServiceHostProvider;
        this.powerManagerProvider = powerManagerProvider;
        this.screenPinningRequestProvider = screenPinningRequestProvider;
        this.dozeScrimControllerProvider = dozeScrimControllerProvider;
        this.volumeComponentProvider = volumeComponentProvider;
        this.commandQueueProvider = commandQueueProvider;
        this.recentsProvider = recentsProvider;
        this.statusBarComponentBuilderProvider = statusBarComponentBuilderProvider;
        this.pluginManagerProvider = pluginManagerProvider;
        this.dividerOptionalProvider = dividerOptionalProvider;
        this.lightsOutNotifControllerProvider = lightsOutNotifControllerProvider;
        this.statusBarNotificationActivityStarterBuilderProvider = statusBarNotificationActivityStarterBuilderProvider;
        this.shadeControllerProvider = shadeControllerProvider;
        this.superStatusBarViewFactoryProvider = superStatusBarViewFactoryProvider;
        this.statusBarKeyguardViewManagerProvider = statusBarKeyguardViewManagerProvider;
        this.viewMediatorCallbackProvider = viewMediatorCallbackProvider;
        this.initControllerProvider = initControllerProvider;
        this.darkIconDispatcherProvider = darkIconDispatcherProvider;
        this.timeTickHandlerProvider = timeTickHandlerProvider;
        this.pluginDependencyProvider = pluginDependencyProvider;
        this.keyguardDismissUtilProvider = keyguardDismissUtilProvider;
        this.extensionControllerProvider = extensionControllerProvider;
        this.userInfoControllerImplProvider = userInfoControllerImplProvider;
        this.phoneStatusBarPolicyProvider = phoneStatusBarPolicyProvider;
        this.keyguardIndicationControllerProvider = keyguardIndicationControllerProvider;
        this.dismissCallbackRegistryProvider = dismissCallbackRegistryProvider;
        this.statusBarTouchableRegionManagerProvider = statusBarTouchableRegionManagerProvider;
    }
    
    public static StatusBarGoogleModule_ProvideStatusBarFactory create(final Provider<SmartSpaceController> provider, final Provider<WallpaperNotifier> provider2, final Provider<Optional<ReverseChargingWindowController>> provider3, final Provider<Context> provider4, final Provider<NotificationsController> provider5, final Provider<LightBarController> provider6, final Provider<AutoHideController> provider7, final Provider<KeyguardUpdateMonitor> provider8, final Provider<StatusBarIconController> provider9, final Provider<PulseExpansionHandler> provider10, final Provider<NotificationWakeUpCoordinator> provider11, final Provider<KeyguardBypassController> provider12, final Provider<KeyguardStateController> provider13, final Provider<HeadsUpManagerPhone> provider14, final Provider<DynamicPrivacyController> provider15, final Provider<BypassHeadsUpNotifier> provider16, final Provider<FalsingManager> provider17, final Provider<BroadcastDispatcher> provider18, final Provider<RemoteInputQuickSettingsDisabler> provider19, final Provider<NotificationGutsManager> provider20, final Provider<NotificationLogger> provider21, final Provider<NotificationInterruptStateProvider> provider22, final Provider<NotificationViewHierarchyManager> provider23, final Provider<KeyguardViewMediator> provider24, final Provider<NotificationAlertingManager> provider25, final Provider<DisplayMetrics> provider26, final Provider<MetricsLogger> provider27, final Provider<Executor> provider28, final Provider<NotificationMediaManager> provider29, final Provider<NotificationLockscreenUserManager> provider30, final Provider<NotificationRemoteInputManager> provider31, final Provider<UserSwitcherController> provider32, final Provider<NetworkController> provider33, final Provider<BatteryController> provider34, final Provider<SysuiColorExtractor> provider35, final Provider<ScreenLifecycle> provider36, final Provider<WakefulnessLifecycle> provider37, final Provider<SysuiStatusBarStateController> provider38, final Provider<VibratorHelper> provider39, final Provider<BubbleController> provider40, final Provider<NotificationGroupManager> provider41, final Provider<VisualStabilityManager> provider42, final Provider<DeviceProvisionedController> provider43, final Provider<NavigationBarController> provider44, final Provider<AssistManager> provider45, final Provider<ConfigurationController> provider46, final Provider<NotificationShadeWindowController> provider47, final Provider<LockscreenLockIconController> provider48, final Provider<DozeParameters> provider49, final Provider<LiveWallpaperScrimController> provider50, final Provider<KeyguardLiftController> provider51, final Provider<LockscreenWallpaper> provider52, final Provider<BiometricUnlockController> provider53, final Provider<NotificationShadeDepthController> provider54, final Provider<DozeServiceHost> provider55, final Provider<PowerManager> provider56, final Provider<ScreenPinningRequest> provider57, final Provider<DozeScrimController> provider58, final Provider<VolumeComponent> provider59, final Provider<CommandQueue> provider60, final Provider<Optional<Recents>> provider61, final Provider<StatusBarComponent.Builder> provider62, final Provider<PluginManager> provider63, final Provider<Optional<Divider>> provider64, final Provider<LightsOutNotifController> provider65, final Provider<StatusBarNotificationActivityStarter.Builder> provider66, final Provider<ShadeController> provider67, final Provider<SuperStatusBarViewFactory> provider68, final Provider<StatusBarKeyguardViewManager> provider69, final Provider<ViewMediatorCallback> provider70, final Provider<InitController> provider71, final Provider<DarkIconDispatcher> provider72, final Provider<Handler> provider73, final Provider<PluginDependencyProvider> provider74, final Provider<KeyguardDismissUtil> provider75, final Provider<ExtensionController> provider76, final Provider<UserInfoControllerImpl> provider77, final Provider<PhoneStatusBarPolicy> provider78, final Provider<KeyguardIndicationController> provider79, final Provider<DismissCallbackRegistry> provider80, final Provider<StatusBarTouchableRegionManager> provider81) {
        return new StatusBarGoogleModule_ProvideStatusBarFactory(provider, provider2, provider3, provider4, provider5, provider6, provider7, provider8, provider9, provider10, provider11, provider12, provider13, provider14, provider15, provider16, provider17, provider18, provider19, provider20, provider21, provider22, provider23, provider24, provider25, provider26, provider27, provider28, provider29, provider30, provider31, provider32, provider33, provider34, provider35, provider36, provider37, provider38, provider39, provider40, provider41, provider42, provider43, provider44, provider45, provider46, provider47, provider48, provider49, provider50, provider51, provider52, provider53, provider54, provider55, provider56, provider57, provider58, provider59, provider60, provider61, provider62, provider63, provider64, provider65, provider66, provider67, provider68, provider69, provider70, provider71, provider72, provider73, provider74, provider75, provider76, provider77, provider78, provider79, provider80, provider81);
    }
    
    public static StatusBarGoogle provideInstance(final Provider<SmartSpaceController> provider, final Provider<WallpaperNotifier> provider2, final Provider<Optional<ReverseChargingWindowController>> provider3, final Provider<Context> provider4, final Provider<NotificationsController> provider5, final Provider<LightBarController> provider6, final Provider<AutoHideController> provider7, final Provider<KeyguardUpdateMonitor> provider8, final Provider<StatusBarIconController> provider9, final Provider<PulseExpansionHandler> provider10, final Provider<NotificationWakeUpCoordinator> provider11, final Provider<KeyguardBypassController> provider12, final Provider<KeyguardStateController> provider13, final Provider<HeadsUpManagerPhone> provider14, final Provider<DynamicPrivacyController> provider15, final Provider<BypassHeadsUpNotifier> provider16, final Provider<FalsingManager> provider17, final Provider<BroadcastDispatcher> provider18, final Provider<RemoteInputQuickSettingsDisabler> provider19, final Provider<NotificationGutsManager> provider20, final Provider<NotificationLogger> provider21, final Provider<NotificationInterruptStateProvider> provider22, final Provider<NotificationViewHierarchyManager> provider23, final Provider<KeyguardViewMediator> provider24, final Provider<NotificationAlertingManager> provider25, final Provider<DisplayMetrics> provider26, final Provider<MetricsLogger> provider27, final Provider<Executor> provider28, final Provider<NotificationMediaManager> provider29, final Provider<NotificationLockscreenUserManager> provider30, final Provider<NotificationRemoteInputManager> provider31, final Provider<UserSwitcherController> provider32, final Provider<NetworkController> provider33, final Provider<BatteryController> provider34, final Provider<SysuiColorExtractor> provider35, final Provider<ScreenLifecycle> provider36, final Provider<WakefulnessLifecycle> provider37, final Provider<SysuiStatusBarStateController> provider38, final Provider<VibratorHelper> provider39, final Provider<BubbleController> provider40, final Provider<NotificationGroupManager> provider41, final Provider<VisualStabilityManager> provider42, final Provider<DeviceProvisionedController> provider43, final Provider<NavigationBarController> provider44, final Provider<AssistManager> provider45, final Provider<ConfigurationController> provider46, final Provider<NotificationShadeWindowController> provider47, final Provider<LockscreenLockIconController> provider48, final Provider<DozeParameters> provider49, final Provider<LiveWallpaperScrimController> provider50, final Provider<KeyguardLiftController> provider51, final Provider<LockscreenWallpaper> provider52, final Provider<BiometricUnlockController> provider53, final Provider<NotificationShadeDepthController> provider54, final Provider<DozeServiceHost> provider55, final Provider<PowerManager> provider56, final Provider<ScreenPinningRequest> provider57, final Provider<DozeScrimController> provider58, final Provider<VolumeComponent> provider59, final Provider<CommandQueue> provider60, final Provider<Optional<Recents>> provider61, final Provider<StatusBarComponent.Builder> provider62, final Provider<PluginManager> provider63, final Provider<Optional<Divider>> provider64, final Provider<LightsOutNotifController> provider65, final Provider<StatusBarNotificationActivityStarter.Builder> provider66, final Provider<ShadeController> provider67, final Provider<SuperStatusBarViewFactory> provider68, final Provider<StatusBarKeyguardViewManager> provider69, final Provider<ViewMediatorCallback> provider70, final Provider<InitController> provider71, final Provider<DarkIconDispatcher> provider72, final Provider<Handler> provider73, final Provider<PluginDependencyProvider> provider74, final Provider<KeyguardDismissUtil> provider75, final Provider<ExtensionController> provider76, final Provider<UserInfoControllerImpl> provider77, final Provider<PhoneStatusBarPolicy> provider78, final Provider<KeyguardIndicationController> provider79, final Provider<DismissCallbackRegistry> provider80, final Provider<StatusBarTouchableRegionManager> provider81) {
        return proxyProvideStatusBar(provider.get(), provider2.get(), provider3.get(), provider4.get(), provider5.get(), provider6.get(), provider7.get(), provider8.get(), provider9.get(), provider10.get(), provider11.get(), provider12.get(), provider13.get(), provider14.get(), provider15.get(), provider16.get(), provider17.get(), provider18.get(), provider19.get(), provider20.get(), provider21.get(), provider22.get(), provider23.get(), provider24.get(), provider25.get(), provider26.get(), provider27.get(), provider28.get(), provider29.get(), provider30.get(), provider31.get(), provider32.get(), provider33.get(), provider34.get(), provider35.get(), provider36.get(), provider37.get(), provider38.get(), provider39.get(), provider40.get(), provider41.get(), provider42.get(), provider43.get(), provider44.get(), DoubleCheck.lazy(provider45), provider46.get(), provider47.get(), provider48.get(), provider49.get(), provider50.get(), provider51.get(), DoubleCheck.lazy(provider52), DoubleCheck.lazy(provider53), DoubleCheck.lazy(provider54), provider55.get(), provider56.get(), provider57.get(), provider58.get(), provider59.get(), provider60.get(), provider61.get(), provider62, provider63.get(), provider64.get(), provider65.get(), provider66.get(), provider67.get(), provider68.get(), provider69.get(), provider70.get(), provider71.get(), provider72.get(), provider73.get(), provider74.get(), provider75.get(), provider76.get(), provider77.get(), provider78.get(), provider79.get(), provider80.get(), provider81.get());
    }
    
    public static StatusBarGoogle proxyProvideStatusBar(final SmartSpaceController smartSpaceController, final WallpaperNotifier wallpaperNotifier, final Optional<ReverseChargingWindowController> optional, final Context context, final NotificationsController notificationsController, final LightBarController lightBarController, final AutoHideController autoHideController, final KeyguardUpdateMonitor keyguardUpdateMonitor, final StatusBarIconController statusBarIconController, final PulseExpansionHandler pulseExpansionHandler, final NotificationWakeUpCoordinator notificationWakeUpCoordinator, final KeyguardBypassController keyguardBypassController, final KeyguardStateController keyguardStateController, final HeadsUpManagerPhone headsUpManagerPhone, final DynamicPrivacyController dynamicPrivacyController, final BypassHeadsUpNotifier bypassHeadsUpNotifier, final FalsingManager falsingManager, final BroadcastDispatcher broadcastDispatcher, final RemoteInputQuickSettingsDisabler remoteInputQuickSettingsDisabler, final NotificationGutsManager notificationGutsManager, final NotificationLogger notificationLogger, final NotificationInterruptStateProvider notificationInterruptStateProvider, final NotificationViewHierarchyManager notificationViewHierarchyManager, final KeyguardViewMediator keyguardViewMediator, final NotificationAlertingManager notificationAlertingManager, final DisplayMetrics displayMetrics, final MetricsLogger metricsLogger, final Executor executor, final NotificationMediaManager notificationMediaManager, final NotificationLockscreenUserManager notificationLockscreenUserManager, final NotificationRemoteInputManager notificationRemoteInputManager, final UserSwitcherController userSwitcherController, final NetworkController networkController, final BatteryController batteryController, final SysuiColorExtractor sysuiColorExtractor, final ScreenLifecycle screenLifecycle, final WakefulnessLifecycle wakefulnessLifecycle, final SysuiStatusBarStateController sysuiStatusBarStateController, final VibratorHelper vibratorHelper, final BubbleController bubbleController, final NotificationGroupManager notificationGroupManager, final VisualStabilityManager visualStabilityManager, final DeviceProvisionedController deviceProvisionedController, final NavigationBarController navigationBarController, final Lazy<AssistManager> lazy, final ConfigurationController configurationController, final NotificationShadeWindowController notificationShadeWindowController, final LockscreenLockIconController lockscreenLockIconController, final DozeParameters dozeParameters, final LiveWallpaperScrimController liveWallpaperScrimController, final KeyguardLiftController keyguardLiftController, final Lazy<LockscreenWallpaper> lazy2, final Lazy<BiometricUnlockController> lazy3, final Lazy<NotificationShadeDepthController> lazy4, final DozeServiceHost dozeServiceHost, final PowerManager powerManager, final ScreenPinningRequest screenPinningRequest, final DozeScrimController dozeScrimController, final VolumeComponent volumeComponent, final CommandQueue commandQueue, final Optional<Recents> optional2, final Provider<StatusBarComponent.Builder> provider, final PluginManager pluginManager, final Optional<Divider> optional3, final LightsOutNotifController lightsOutNotifController, final StatusBarNotificationActivityStarter.Builder builder, final ShadeController shadeController, final SuperStatusBarViewFactory superStatusBarViewFactory, final StatusBarKeyguardViewManager statusBarKeyguardViewManager, final ViewMediatorCallback viewMediatorCallback, final InitController initController, final DarkIconDispatcher darkIconDispatcher, final Handler handler, final PluginDependencyProvider pluginDependencyProvider, final KeyguardDismissUtil keyguardDismissUtil, final ExtensionController extensionController, final UserInfoControllerImpl userInfoControllerImpl, final PhoneStatusBarPolicy phoneStatusBarPolicy, final KeyguardIndicationController keyguardIndicationController, final DismissCallbackRegistry dismissCallbackRegistry, final StatusBarTouchableRegionManager statusBarTouchableRegionManager) {
        final StatusBarGoogle provideStatusBar = StatusBarGoogleModule.provideStatusBar(smartSpaceController, wallpaperNotifier, optional, context, notificationsController, lightBarController, autoHideController, keyguardUpdateMonitor, statusBarIconController, pulseExpansionHandler, notificationWakeUpCoordinator, keyguardBypassController, keyguardStateController, headsUpManagerPhone, dynamicPrivacyController, bypassHeadsUpNotifier, falsingManager, broadcastDispatcher, remoteInputQuickSettingsDisabler, notificationGutsManager, notificationLogger, notificationInterruptStateProvider, notificationViewHierarchyManager, keyguardViewMediator, notificationAlertingManager, displayMetrics, metricsLogger, executor, notificationMediaManager, notificationLockscreenUserManager, notificationRemoteInputManager, userSwitcherController, networkController, batteryController, sysuiColorExtractor, screenLifecycle, wakefulnessLifecycle, sysuiStatusBarStateController, vibratorHelper, bubbleController, notificationGroupManager, visualStabilityManager, deviceProvisionedController, navigationBarController, lazy, configurationController, notificationShadeWindowController, lockscreenLockIconController, dozeParameters, liveWallpaperScrimController, keyguardLiftController, lazy2, lazy3, lazy4, dozeServiceHost, powerManager, screenPinningRequest, dozeScrimController, volumeComponent, commandQueue, optional2, provider, pluginManager, optional3, lightsOutNotifController, builder, shadeController, superStatusBarViewFactory, statusBarKeyguardViewManager, viewMediatorCallback, initController, darkIconDispatcher, handler, pluginDependencyProvider, keyguardDismissUtil, extensionController, userInfoControllerImpl, phoneStatusBarPolicy, keyguardIndicationController, dismissCallbackRegistry, statusBarTouchableRegionManager);
        Preconditions.checkNotNull(provideStatusBar, "Cannot return null from a non-@Nullable @Provides method");
        return provideStatusBar;
    }
    
    @Override
    public StatusBarGoogle get() {
        return provideInstance(this.smartSpaceControllerProvider, this.wallpaperNotifierProvider, this.reverseChargingWindowControllerOptionalProvider, this.contextProvider, this.notificationsControllerProvider, this.lightBarControllerProvider, this.autoHideControllerProvider, this.keyguardUpdateMonitorProvider, this.statusBarIconControllerProvider, this.pulseExpansionHandlerProvider, this.notificationWakeUpCoordinatorProvider, this.keyguardBypassControllerProvider, this.keyguardStateControllerProvider, this.headsUpManagerPhoneProvider, this.dynamicPrivacyControllerProvider, this.bypassHeadsUpNotifierProvider, this.falsingManagerProvider, this.broadcastDispatcherProvider, this.remoteInputQuickSettingsDisablerProvider, this.notificationGutsManagerProvider, this.notificationLoggerProvider, this.notificationInterruptionStateProvider, this.notificationViewHierarchyManagerProvider, this.keyguardViewMediatorProvider, this.notificationAlertingManagerProvider, this.displayMetricsProvider, this.metricsLoggerProvider, this.uiBgExecutorProvider, this.notificationMediaManagerProvider, this.lockScreenUserManagerProvider, this.remoteInputManagerProvider, this.userSwitcherControllerProvider, this.networkControllerProvider, this.batteryControllerProvider, this.colorExtractorProvider, this.screenLifecycleProvider, this.wakefulnessLifecycleProvider, this.statusBarStateControllerProvider, this.vibratorHelperProvider, this.bubbleControllerProvider, this.groupManagerProvider, this.visualStabilityManagerProvider, this.deviceProvisionedControllerProvider, this.navigationBarControllerProvider, this.assistManagerLazyProvider, this.configurationControllerProvider, this.notificationShadeWindowControllerProvider, this.lockscreenLockIconControllerProvider, this.dozeParametersProvider, this.scrimControllerProvider, this.keyguardLiftControllerProvider, this.lockscreenWallpaperLazyProvider, this.biometricUnlockControllerLazyProvider, this.notificationShadeDepthControllerLazyProvider, this.dozeServiceHostProvider, this.powerManagerProvider, this.screenPinningRequestProvider, this.dozeScrimControllerProvider, this.volumeComponentProvider, this.commandQueueProvider, this.recentsProvider, this.statusBarComponentBuilderProvider, this.pluginManagerProvider, this.dividerOptionalProvider, this.lightsOutNotifControllerProvider, this.statusBarNotificationActivityStarterBuilderProvider, this.shadeControllerProvider, this.superStatusBarViewFactoryProvider, this.statusBarKeyguardViewManagerProvider, this.viewMediatorCallbackProvider, this.initControllerProvider, this.darkIconDispatcherProvider, this.timeTickHandlerProvider, this.pluginDependencyProvider, this.keyguardDismissUtilProvider, this.extensionControllerProvider, this.userInfoControllerImplProvider, this.phoneStatusBarPolicyProvider, this.keyguardIndicationControllerProvider, this.dismissCallbackRegistryProvider, this.statusBarTouchableRegionManagerProvider);
    }
}
